# https://github.com/probot/settings

branches:
  - name: "master"

    # https://docs.github.com/en/rest/reference/repos#delete-branch-protection
    # https://docs.github.com/en/rest/reference/repos#update-branch-protection

    protection:
      enforce_admins: false
      required_pull_request_reviews:
        dismiss_stale_reviews: true
        require_code_owner_reviews: true
        required_approving_review_count: 1
      required_status_checks:
        contexts:
          - "Code Coverage (7.4, locked)"
          - "Coding Standards (7.4, locked)"
          - "Dependency Analysis (7.4, locked)"
          - "Static Code Analysis (7.4, locked)"
          - "Tests (chrome, 7.2, highest)"
          - "Tests (chrome, 7.2, locked)"
          - "Tests (chrome, 7.2, lowest)"
          - "Tests (chrome, 7.3, highest)"
          - "Tests (chrome, 7.3, locked)"
          - "Tests (chrome, 7.3, lowest)"
          - "Tests (chrome, 7.4, highest)"
          - "Tests (chrome, 7.4, locked)"
          - "Tests (chrome, 7.4, lowest)"
          - "Tests (firefox, 7.2, highest)"
          - "Tests (firefox, 7.2, locked)"
          - "Tests (firefox, 7.2, lowest)"
          - "Tests (firefox, 7.3, highest)"
          - "Tests (firefox, 7.3, locked)"
          - "Tests (firefox, 7.3, lowest)"
          - "Tests (firefox, 7.4, highest)"
          - "Tests (firefox, 7.4, locked)"
          - "Tests (firefox, 7.4, lowest)"
          - "Tests (selenium, 7.2, highest)"
          - "Tests (selenium, 7.2, locked)"
          - "Tests (selenium, 7.2, lowest)"
          - "Tests (selenium, 7.3, highest)"
          - "Tests (selenium, 7.3, locked)"
          - "Tests (selenium, 7.3, lowest)"
          - "Tests (selenium, 7.4, highest)"
          - "Tests (selenium, 7.4, locked)"
          - "Tests (selenium, 7.4, lowest)"
        strict: false
      restrictions: null

# https://docs.github.com/en/rest/reference/issues#create-a-label
# https://docs.github.com/en/rest/reference/issues#update-a-label

labels:
  - name: "bug"
    color: "ee0701"
    description: ""

  - name: "dependency"
    color: "0366d6"
    description: ""

  - name: "enhancement"
    color: "0e8a16"
    description: ""

  - name: "merge"
    color: "6f42c1"
    description: ""

  - name: "question"
    color: "cc317c"
    description: ""

  - name: "security"
    color: "ee0701"
    description: ""

  - name: "stale"
    color: "eeeeee"
    description: ""

# https://docs.github.com/en/rest/reference/repos#update-a-repository

repository:
  allow_merge_commit: true
  allow_rebase_merge: false
  allow_squash_merge: false
  archived: true
  default_branch: "master"
  delete_branch_on_merge: true
  description: ""
  has_downloads: true
  has_issues: true
  has_pages: false
  has_projects: false
  has_wiki: false
  name: "mink-panther-driver"
  private: false

  # https://docs.github.com/en/rest/reference/repos#replace-all-repository-topics

  topics: ""
