language: php

if: type != push OR branch = master OR branch =~ /^v\d+\.\d+(\.\d+)?(-\S*)?$/

cache:
  directories:
    - $HOME/.composer/cache

matrix:
  allow_failures:
    - php: 7.4snapshot
    - php: nightly

_install_scripts: &install_scripts
  install:
    - travis_retry sh .travis.install.sh

_test_scripts: &test_scripts
  <<: *install_scripts
  before_script:
    - bin/mink-test-server > /dev/null 2>&1 &
  script:
    - vendor/bin/phpunit -v

_browsers:
  chrome: &chrome
    addons:
      chrome: stable
    before_install:
      - phpenv config-rm xdebug.ini || true
      - curl -OLsS https://chromedriver.storage.googleapis.com/$(curl -L https://chromedriver.storage.googleapis.com/LATEST_RELEASE)/chromedriver_linux64.zip
      - unzip chromedriver_linux64.zip
  selenium-chrome: &selenium-chrome
    before_install:
      - phpenv config-rm xdebug.ini || true
      - docker run -d --network=host selenium/standalone-chrome:latest
      - |
        while ! curl -sSL "http://localhost:4444/wd/hub/status" 2>&1 \
                | jq -r '.value.ready' 2>&1 | grep "true" >/dev/null; do
            echo 'Waiting for Selenium'
            sleep 1
        done
  selenium-firefox: &selenium-firefox
    before_install:
      - phpenv config-rm xdebug.ini || true
      # do not use newer version, firefox is following w3c much faster then drivers
      - docker run -d --network=host selenium/standalone-firefox:2.53.1

jobs:
  include:
    # Chromedriver builds
    - stage: Test
      php: 7.2
      env:
        - DEPENDENCIES="high"
        - PANTHER_CHROME_DRIVER_BINARY="./chromedriver"
      <<: *chrome
      <<: *test_scripts
    
    - stage: Test
      php: 7.2
      env:
        - DEPENDENCIES="low"
        - PANTHER_CHROME_DRIVER_BINARY="./chromedriver"
      <<: *chrome
      <<: *test_scripts
    
    - stage: Test
      php: 7.3
      env:
        - DEPENDENCIES="high"
        - PANTHER_CHROME_DRIVER_BINARY="./chromedriver"
      <<: *chrome
      <<: *test_scripts
    
    - stage: Test
      php: 7.3
      env:
        - DEPENDENCIES="low"
        - PANTHER_CHROME_DRIVER_BINARY="./chromedriver"
      <<: *chrome
      <<: *test_scripts
    
    - stage: Test
      php: 7.4snapshot
      env:
        - DEPENDENCIES="high"
        - PANTHER_CHROME_DRIVER_BINARY="./chromedriver"
      <<: *chrome
      <<: *test_scripts
    
    - stage: Test
      php: 7.4snapshot
      env:
        - DEPENDENCIES="low"
        - PANTHER_CHROME_DRIVER_BINARY="./chromedriver"
      <<: *chrome
      <<: *test_scripts
    
    - stage: Test
      php: nightly
      env:
        - DEPENDENCIES="high"
        - PANTHER_CHROME_DRIVER_BINARY="./chromedriver"
      <<: *chrome
      <<: *test_scripts
    
    - stage: Test
      php: nightly
      env:
        - DEPENDENCIES="low"
        - PANTHER_CHROME_DRIVER_BINARY="./chromedriver"
      <<: *chrome
      <<: *test_scripts
    
    # Selenium firefox builds
    - stage: Test
      php: 7.2
      env:
        - DEPENDENCIES="high"
        - SELENIUM=1
        - BROWSER_NAME="firefox"
      <<: *selenium-firefox
      <<: *test_scripts
    
    - stage: Test
      php: 7.2
      env:
        - DEPENDENCIES="low"
        - SELENIUM=1
        - BROWSER_NAME="firefox"
      <<: *selenium-firefox
      <<: *test_scripts
    
    - stage: Test
      php: 7.3
      env:
        - DEPENDENCIES="high"
        - SELENIUM=1
        - BROWSER_NAME="firefox"
      <<: *selenium-firefox
      <<: *test_scripts
    
    - stage: Test
      php: 7.3
      env:
        - DEPENDENCIES="low"
        - SELENIUM=1
        - BROWSER_NAME="firefox"
      <<: *selenium-firefox
      <<: *test_scripts
    
    # Selenium chrome builds
    - stage: Test
      php: 7.2
      env:
        - DEPENDENCIES="high"
        - SELENIUM=1
        - BROWSER_NAME="chrome"
      <<: *selenium-chrome
      <<: *test_scripts
    
    - stage: Test
      php: 7.2
      env:
        - DEPENDENCIES="low"
        - SELENIUM=1
        - BROWSER_NAME="chrome"
      <<: *selenium-chrome
      <<: *test_scripts
    
    - stage: Test
      php: 7.3
      env:
        - DEPENDENCIES="high"
        - SELENIUM=1
        - BROWSER_NAME="chrome"
      <<: *selenium-chrome
      <<: *test_scripts
    
    - stage: Test
      php: 7.3
      env:
        - DEPENDENCIES="low"
        - SELENIUM=1
        - BROWSER_NAME="chrome"
      <<: *selenium-chrome
      <<: *test_scripts
