language: php

if: type != push OR branch = master OR branch =~ /^v\d+\.\d+(\.\d+)?(-\S*)?$/

cache:
  directories:
    - $HOME/.composer/cache

matrix:
  allow_failures:
    - php: 7.4snapshot
    - php: nightly

_install_scripts: &install_scripts
  install:
    - travis_retry sh .travis.install.sh

_test_scripts: &test_scripts
  <<: *install_scripts
  before_script:
    - vendor/bin/mink-test-server > /dev/null 2>&1 &
  script:
    - vendor/bin/phpunit -v

_browsers:
  chrome: &chrome
    addons:
      chrome: stable
    before_install:
      - phpenv config-rm xdebug.ini || true
      - |
        mkdir -p .build/chromedriver
        chromeversion=$(google-chrome --product-version)
        chromeversion=${chromeversion%.*}
        curl -LsS -o .build/chromedriver/chromedriver.zip https://chromedriver.storage.googleapis.com/$(curl -L https://chromedriver.storage.googleapis.com/LATEST_RELEASE_${chromeversion})/chromedriver_linux64.zip
        unzip .build/chromedriver/chromedriver.zip -d .build/chromedriver

jobs:
  include:
    # Test against latest Symfony 4.4 beta
    - stage: Test
      php: 7.3
      env:
        - SYMFONY_VERSION="4.4.*@beta"
        - DEPENDENCIES="high"
        - PANTHER_CHROME_DRIVER_BINARY=".build/chromedriver/chromedriver"
      <<: *chrome
      <<: *test_scripts
