# https://help.github.com/en/categories/automating-your-workflow-with-github-actions

on:
  pull_request:
  push:
    branches:
      - master
    tags:
      - "**"

name: "Continuous Integration"

jobs:
  coding-standards:
    name: "Coding Standards"
    
    runs-on: ubuntu-latest
    
    steps:
      - name: "Checkout"
        uses: actions/checkout@v1.1.0
      
      - name: "Disable Xdebug"
        run: php7.2 --ini | grep xdebug | sed 's/,$//' | xargs sudo rm
      
      - name: "Validate composer.json and composer.lock"
        run: php7.2 $(which composer) validate --strict
      
      - name: "Cache dependencies installed with composer"
        uses: actions/cache@v1.0.1
        with:
          path: ~/.composer/cache
          key: php7.2-composer-locked-${{ hashFiles('**/composer.lock') }}
          restore-keys: |
            php7.2-composer-locked-
      
      - name: "Install locked dependencies with composer"
        run: php7.2 $(which composer) install --no-interaction --no-progress --no-suggest
      
      - name: "Run localheinz/composer-normalize"
        run: php7.2 $(which composer) normalize --dry-run
      
      - name: "Run doctrine/coding-standard"
        run: php7.2 vendor/bin/phpcs
      
      - name: "Run maglnet/composer-require-checker"
        run: php7.2 vendor/bin/composer-require-checker
  
  static-code-analysis:
    name: "Static Code Analysis"
    
    runs-on: ubuntu-latest
    
    steps:
      - name: "Checkout"
        uses: actions/checkout@v1.1.0
      
      - name: "Disable Xdebug"
        run: php7.3 --ini | grep xdebug | sed 's/,$//' | xargs sudo rm
      
      - name: "Cache dependencies installed with composer"
        uses: actions/cache@v1.0.1
        with:
          path: ~/.composer/cache
          key: php7.3-composer-locked-${{ hashFiles('**/composer.lock') }}
          restore-keys: |
            php7.3-composer-locked-
      
      - name: "Install locked dependencies with composer"
        run: php7.3 $(which composer) install --no-interaction --no-progress --no-suggest
      
      - name: "Run phpstan/phpstan"
        run: php7.3 vendor/bin/phpstan analyse
